### ISSUE TITLE
Update brew

### ISSUE THREAD

**Issue by victordidenko** [xxczaki/cash-cli#25]
Hello!
Could you please update **brew** formula to the latest version?
Now it is 2.0.8

**Comment by xxczaki** [comment]
@victordidenko Hi! Sorry for the delay, I will try to update it in the next few days :smile:

**Comment by xxczaki** [comment]
https://github.com/Homebrew/homebrew-core/pull/37292

**Comment by victordidenko** [comment]
$ brew info cash-cli
cash-cli: stable 3.0.0 (bottled)
Exchange Currency Rates using your terminal
https://github.com/xxczaki/cash-cli
/usr/local/Cellar/cash-cli/3.0.0 (577 files, 1.2MB) *
