### ISSUE TITLE
Help message doesn't reflect reality

### ISSUE THREAD

**Issue by victordidenko** [xxczaki/cash-cli#27]
https://github.com/xxczaki/cash-cli/blob/0e3711e21e3e7bfc332b88ee69e681964f5c2ceb/bin/index.js#L19

Help shows `--set` argument key, while later in code `--save` is used

https://github.com/xxczaki/cash-cli/blob/0e3711e21e3e7bfc332b88ee69e681964f5c2ceb/bin/index.js#L42

**Comment by xxczaki** [comment]
@victordidenko Thanks! It is now fixed in 3.0.1 :smile:
