### ISSUE TITLE
Homebrew 3.1.2 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [xxczaki/cash-cli#30]
Relates to https://github.com/Homebrew/homebrew-core/pull/40673

Having issue with `cash 10 usd eur pln` and `cash -key foo`

```
$ /usr/local/Cellar/cash-cli/3.1.0/bin/cash 10 usd eur pln
/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58
				throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
				^

Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Conf (/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58:11)
    at Object.<anonymous> (/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/bin/cash.js:10:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/bin/index.js:9:14)
```

```
$ /usr/local/Cellar/cash-cli/3.1.0/bin/cash -key foo
/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58
				throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
				^

Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Conf (/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58:11)
    at Object.<anonymous> (/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/bin/cash.js:10:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/bin/index.js:9:14)
```

**Comment by xxczaki** [comment]
Hi @chenrui333, sorry for the delay, but I was on holiday in Spain this week ;)

In 3.1.0 I added the [API key validation](https://github.com/xxczaki/cash-cli/blob/ce6f9cce8d6be39cd195f72a8625a76ade72ecb6/bin/index.js#L42), so the output of `cash --key foo` is now: `Provided API key seems invalid, please try again!` and not: `'Saved API key to [...]`. To fix that, we can either change [this line](https://github.com/Homebrew/homebrew-core/blob/80745d7975635f4895ab9a04efce2b23bbe46f31/Formula/cash-cli.rb#L24) to:
```ruby
assert_match "Provided API key seems invalid, please try again!"
```
or we can change the test command from `cash --key foo` to something like `cash --key 11111111111111111111111111111111` and keep `assert_match` the same as before. 

Let me know which option is better and I will open a pull request to the Homebrew repo :smile:

**Comment by chenrui333** [comment]
cool, welcome back!

I am outside now, I will check later tonight or tomorrow. Thanks for checking on this!

**Comment by chenrui333** [comment]
Sorry for trying this late. It seems still not quite working.

I have directly called the command and get the following output:
```
$ /usr/local/Cellar/cash-cli/3.1.0/bin/cash --key 111111111111111111111111111111
/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58
				throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
				^

Error: Project name could not be inferred. Please specify the `projectName` option.
```

**Comment by chenrui333** [comment]
It also looks like there is no help cli option:
```
$  /usr/local/Cellar/cash-cli/3.1.0/bin/cash help
/usr/local/Cellar/cash-cli/3.1.0/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58
				throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
				^

Error: Project name could not be inferred. Please specify the `projectName` option.
```

**Comment by xxczaki** [comment]
Could you try it with the newest `3.1.1` version? Something was wrong with the `conf` module, but it's now updated, so everything should be working fine :smile:

**Comment by chenrui333** [comment]
Definitely, doing it now.

**Comment by chenrui333** [comment]
Still had the same issue:
```
06:40:22 ==> /usr/local/Cellar/cash-cli/3.1.1/bin/cash --key foo
06:40:22 /usr/local/Cellar/cash-cli/3.1.1/libexec/lib/node_modules/cash-cli/node_modules/conf/index.js:58
06:40:22 				throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
06:40:22 				^
06:40:22 
06:40:22 Error: Project name could not be inferred. Please specify the `projectName` option.
```

**Comment by chenrui333** [comment]
@xxczaki ping. :)

**Comment by xxczaki** [comment]
@chenrui333 Ouch, I totally forgot about that! Well, after investigating [this](https://github.com/sindresorhus/conf/pull/6) issue I realised, that adding a `projectName` to `conf` module options should fix our problem. 

Just published `3.1.2` :smile: Let me know if everything works now (and if not I will open an issue in the `conf` repository).

**Comment by xxczaki** [comment]
Sorry! Accidentally closed it :laughing:

**Comment by chenrui333** [comment]
cool!, will try the new one, cheers!

**Comment by chenrui333** [comment]
@xxczaki Still failed (build ref: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/44594/version=mojave/console)

07:21:13 ==> /usr/local/Cellar/cash-cli/3.1.2/bin/cash --key foo
07:21:13 Error: cash-cli: failed
07:21:13 An exception occurred within a child process:
07:21:13   Test::Unit::AssertionFailedError: <0> expected but was

**Comment by xxczaki** [comment]
Hmm, error message doesn’t make much sense. Will look at it later today.

**Comment by xxczaki** [comment]
@chenrui333 Hi, I created a [pull request](https://github.com/Homebrew/homebrew-core/pull/42259) in the Homebrew/homebrew-core repository with changes I suggested in https://github.com/xxczaki/cash-cli/issues/30#issuecomment-500244690 . It passed the [test](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/45448/).

I have no idea why it wasn't working when you tried it in the console.

What should we do?

**Comment by chenrui333** [comment]
that is cool!! I will close my PR in favor of yours. :)

**Comment by chenrui333** [comment]
I could remember the details, but it might be because i was just using your suggestion in 3.1.0, and now we are in 3.1.2. I will try to see if it works in my local though.

**Comment by chenrui333** [comment]
yeah, it works in my local too.

**Comment by chenrui333** [comment]
One thing you should do is to rename the commit and PR title as `cash-cli: 3.1.2`, and we are good to go. 🎉

**Comment by xxczaki** [comment]
@chenrui333 done :smile:

**Comment by chenrui333** [comment]
Thanks a lot!! Closing my issue now.
