### ISSUE TITLE
Support for Fixer-compatible API sources

### ISSUE THREAD

**Issue by bxio** [xxczaki/cash-cli#33]
It's trivial to support [Exchange Rates API](https://exchangeratesapi.io/) and others that are fixer.io compatible. Perhaps give users a choice on which API to query from.

**Comment by xxczaki** [comment]
Good idea! I will try to implement API source selection :smile:

**Comment by xxczaki** [comment]
@bxio The latest version (`4.0.0`) now supports multiple APIs :smile:

You can choose the API source by running `cash --api`.

Currently supported APIs include:

- [Exchange Rates API (default)](https://exchangeratesapi.io/)
- [Fixer](https://fixer.io/)
- [Currency Layer](https://currencylayer.com/)
- [Open Exchange Rates](https://openexchangerates.org/)

Thank you for your suggestion!
