### ISSUE TITLE
Setting default currencies

### ISSUE THREAD

**Issue by bjesus** [xxczaki/cash-cli#5]
Hi! Thanks for cash-cli, it works beautifully.

Is there a way to set the default currencies somehow? So that whatever I throw at `cash` I'll get them back? Right now it seems that the default is set to USD, EUR, GBP and BRL, but I was wondering if this shouldn't be configurable.

Thank you!

**Comment by xxczaki** [comment]
Hi,
Currently you can't configure the default currencies, but thanks for the idea! I will try to make them configurable in the next few days :smiley:

**Comment by xxczaki** [comment]
#7
